#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# Varpulis Demo — One-command install/update
#
# Install:  curl -sSL https://raw.githubusercontent.com/varpulis/varpulis/main/deploy/demo/install.sh | bash
# Update:   same command (idempotent)
#
# Prerequisites:
#   - Docker + Docker Compose v2
#   - TLS certs at /etc/caddy/certs/origin.pem and origin-key.pem
#   - Port 80 and 443 open
#
# What this does:
#   1. Clones (or updates) the varpulis repo
#   2. Generates .env with random API key if missing
#   3. Pulls pre-built Docker images from GHCR (no Rust compile!)
#   4. Starts all services (coordinator ×3, worker ×4, Caddy, Kafka, etc.)
#   5. Waits for coordinator health
#   6. Runs the setup container (creates connectors + deploys pipeline)
#
# Typical runtime: ~30s update, ~2min fresh install (image pull)
# ============================================================================

DEMO_DIR="${VARPULIS_DEMO_DIR:-$HOME/varpulis-demo}"
REPO_URL="https://github.com/varpulis/varpulis.git"
BRANCH="${VARPULIS_BRANCH:-main}"
COMPOSE_DIR="$DEMO_DIR/repo/deploy/demo"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}==>${NC} $1"; }
warn()  { echo -e "${YELLOW}==>${NC} $1"; }
fail()  { echo -e "${RED}ERROR:${NC} $1"; exit 1; }

# ─── Preflight checks ──────────────────────────────────────────────────────

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║       Varpulis Demo Installer            ║"
echo "╚══════════════════════════════════════════╝"
echo ""

command -v docker >/dev/null 2>&1 || fail "Docker not found. Install: curl -fsSL https://get.docker.com | sh"
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 not found. Install: apt-get install docker-compose-v2"

if ! docker info >/dev/null 2>&1; then
    fail "Docker daemon not running, or current user not in docker group"
fi

# ─── Clone or update repo ──────────────────────────────────────────────────

if [ -d "$DEMO_DIR/repo/.git" ]; then
    info "Updating existing repo..."
    cd "$DEMO_DIR/repo"
    git fetch origin "$BRANCH" --quiet
    git reset --hard "origin/$BRANCH" --quiet 2>/dev/null || git reset --hard "origin/$BRANCH"
    info "Repo updated to latest $BRANCH"
else
    info "Cloning varpulis repo..."
    mkdir -p "$DEMO_DIR"
    git clone --branch "$BRANCH" --depth 1 "$REPO_URL" "$DEMO_DIR/repo"
    info "Repo cloned"
fi

cd "$COMPOSE_DIR"

# ─── TLS certs check ───────────────────────────────────────────────────────

if [ ! -f "/etc/caddy/certs/origin.pem" ]; then
    warn "No TLS certs found at /etc/caddy/certs/origin.pem"
    warn "Caddy will fail to start. Place your origin cert + key there first."
    warn "Continuing anyway (non-TLS services will work)..."
fi

# ─── Generate .env if missing ──────────────────────────────────────────────

ENV_FILE="$COMPOSE_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
    API_KEY=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | xxd -p | head -c 32)
    JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | xxd -p | head -c 64)
    GRAFANA_PASS=$(openssl rand -hex 12 2>/dev/null || head -c 24 /dev/urandom | xxd -p | head -c 24)
    PG_PASS=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | xxd -p | head -c 32)

    cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
VARPULIS_API_KEY=$API_KEY
VARPULIS_WORKER_KEY=$API_KEY
RUST_LOG=info
GRAFANA_USER=admin
GRAFANA_PASSWORD=$GRAFANA_PASS
POSTGRES_PASSWORD=$PG_PASS
JWT_SECRET=$JWT_SECRET
EOF
    info "Generated .env with API key: $API_KEY"
else
    info "Using existing .env"
fi

# ─── Pull pre-built images from GHCR ───────────────────────────────────────

info "Pulling pre-built images from GHCR (no Rust compile)..."
docker compose -f docker-compose.yml -f docker-compose.prod.yml pull --quiet 2>/dev/null \
    || docker compose -f docker-compose.yml -f docker-compose.prod.yml pull

# ─── Stop existing services (if running) ────────────────────────────────────

if docker compose ps --quiet 2>/dev/null | head -1 | grep -q .; then
    info "Stopping existing services..."
    docker compose -f docker-compose.yml -f docker-compose.prod.yml down --timeout 15 2>/dev/null || true
fi

# ─── Start services ─────────────────────────────────────────────────────────

info "Starting services..."
docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --no-build

# ─── Wait for coordinator health ────────────────────────────────────────────

info "Waiting for coordinator-1 health..."
for i in $(seq 1 90); do
    if docker compose exec -T coordinator-1 curl -sf http://localhost:9100/health >/dev/null 2>&1; then
        info "Coordinator-1 healthy (${i}s)"
        break
    fi
    if [ "$i" -eq 90 ]; then
        warn "Coordinator not healthy after 90s — check logs: docker compose logs coordinator-1"
    fi
    sleep 1
done

# ─── Wait for Kafka (setup needs it) ────────────────────────────────────────

info "Waiting for Kafka..."
for i in $(seq 1 60); do
    if docker compose exec -T kafka kafka-topics --bootstrap-server localhost:9092 --list >/dev/null 2>&1; then
        info "Kafka ready (${i}s)"
        break
    fi
    if [ "$i" -eq 60 ]; then
        warn "Kafka not ready after 60s — setup may fail"
    fi
    sleep 1
done

# ─── Run setup (create connectors + deploy pipeline) ────────────────────────

info "Running setup (connectors + pipeline)..."
docker compose -f docker-compose.yml -f docker-compose.prod.yml run --rm setup 2>&1 | tail -10 || warn "Setup had errors — check: docker compose logs setup"

# ─── Verify ─────────────────────────────────────────────────────────────────

echo ""
info "Checking service status..."
echo ""
docker compose -f docker-compose.yml -f docker-compose.prod.yml ps --format "table {{.Name}}\t{{.Status}}\t{{.Ports}}" 2>/dev/null \
    || docker compose -f docker-compose.yml -f docker-compose.prod.yml ps

# ─── Print summary ──────────────────────────────────────────────────────────

API_KEY=$(grep VARPULIS_API_KEY "$ENV_FILE" | head -1 | cut -d= -f2)

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                    Varpulis Demo Ready                      ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "  Dashboard:  https://demo.varpulis-cep.com"
echo "  API key:    $API_KEY"
echo "  Grafana:    https://demo.varpulis-cep.com/grafana"
echo ""
echo "  Useful commands (run from $COMPOSE_DIR):"
echo "    docker compose -f docker-compose.yml -f docker-compose.prod.yml logs -f worker-0"
echo "    docker compose -f docker-compose.yml -f docker-compose.prod.yml ps"
echo "    docker compose -f docker-compose.yml -f docker-compose.prod.yml down"
echo ""
echo "  Update:  curl -sSL https://raw.githubusercontent.com/varpulis/varpulis/main/deploy/demo/install.sh | bash"
echo ""
