[package]
name = "varpulis-sase"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "SASE+ pattern matching engine for Complex Event Processing"

[dependencies]
varpulis-core = { version = "0.4.1", path = "../varpulis-core" }
varpulis-zdd = { version = "0.4.1", path = "../varpulis-zdd" }
chrono = { workspace = true }
rustc-hash = { workspace = true }

[lints]
workspace = true
