#!/usr/bin/env bash
# demos/security-consulting/run-assessment.sh
#
# Self-contained security rule assessment demo.
# Runs Varpulis detect + analyze against included datasets
# and produces a coverage report.
#
# Usage:
#   ./run-assessment.sh                  # Run with bundled test data
#   ./run-assessment.sh --events FILE    # Run against your own Sysmon JSONL

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
VARPULIS="${PROJECT_ROOT}/target/release/varpulis"
RULES_DIR="${PROJECT_ROOT}/examples/security-demo"
SIGMA_DIR="${PROJECT_ROOT}/examples/security-demo/sigma_comparison"
REPORT_FILE="${SCRIPT_DIR}/assessment-report.md"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

info() { echo -e "${BLUE}[*]${NC} $*"; }
ok()   { echo -e "${GREEN}[+]${NC} $*"; }

# Check binary
if [[ ! -x "$VARPULIS" ]]; then
    info "Building Varpulis (release)..."
    cargo build --release -p varpulis-cli 2>&1 | tail -1
fi

# Parse args
CUSTOM_EVENTS=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --events) CUSTOM_EVENTS="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

echo ""
echo -e "${BOLD}================================================${NC}"
echo -e "${BOLD}  Varpulis Security Rule Assessment${NC}"
echo -e "${BOLD}================================================${NC}"
echo ""

# ─── Part 1: Kill Chain Detection ───────────────────────────────────────

info "Part 1: Kill Chain Detection"
echo ""

EVENTS="${CUSTOM_EVENTS:-${RULES_DIR}/data/apt29_full_chain.jsonl}"

RUST_LOG=warn "$VARPULIS" detect \
    --rules "$RULES_DIR" \
    --events "$EVENTS" \
    -w 1

echo ""

# ─── Part 2: Evasion Analysis ──────────────────────────────────────────

info "Part 2: Evasion Resilience Analysis"
echo ""

RUST_LOG=warn "$VARPULIS" analyze \
    --rules "$SIGMA_DIR" \
    --baseline "$SIGMA_DIR/normal_dataset.jsonl" \
    --evasion "$SIGMA_DIR/evasion_dataset.jsonl"

echo ""

# ─── Part 3: Generate Markdown Report ─────────────────────────────────

info "Part 3: Generating assessment report..."

{
    echo "# Security Rule Assessment Report"
    echo ""
    echo "**Date:** $(date -u +%Y-%m-%d)"
    echo "**Tool:** Varpulis v$($VARPULIS --version | cut -d' ' -f2)"
    echo ""
    echo "## Kill Chain Detection Results"
    echo ""
    RUST_LOG=error "$VARPULIS" detect \
        --rules "$RULES_DIR" \
        --events "$EVENTS" \
        -w 1 --format markdown 2>/dev/null || true
    echo ""
    echo "## Evasion Resilience Analysis"
    echo ""
    RUST_LOG=error "$VARPULIS" analyze \
        --rules "$SIGMA_DIR" \
        --baseline "$SIGMA_DIR/normal_dataset.jsonl" \
        --evasion "$SIGMA_DIR/evasion_dataset.jsonl" \
        --format markdown 2>/dev/null
    echo ""
    echo "## Recommendations"
    echo ""
    echo "1. Replace signature-based Sigma rules (EVADABLE) with behavioral VPL equivalents"
    echo "2. Deploy Varpulis alongside existing SIEM for behavioral sequence detection"
    echo "3. Run \`varpulis analyze\` regularly against new evasion datasets to track coverage"
    echo ""
    echo "---"
    echo "*Generated by Varpulis Security Assessment*"
} > "$REPORT_FILE"

ok "Report written to: $REPORT_FILE"
echo ""
