[package]
name = "varpulis-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Core types and AST for VPL"

[dependencies]
serde = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
indexmap = { workspace = true }
rustc-hash = { workspace = true }
zeroize = { workspace = true }
miette = { workspace = true }

[dev-dependencies]
varpulis-parser = { path = "../varpulis-parser" }
serde_json = { workspace = true }

[lints]
workspace = true
