[package]
name = "varpulis-connector-http"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "HTTP connector for Varpulis CEP engine"

[dependencies]
varpulis-connector-api = { version = "0.9.0", path = "../varpulis-connector-api" }
varpulis-core = { version = "0.9.0", path = "../varpulis-core" }
reqwest = { workspace = true }
axum = { workspace = true }
tower-http = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
tracing = { workspace = true }
indexmap = { workspace = true }
inventory = { workspace = true }
async-trait = "0.1"

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }

[lints]
workspace = true
